# Generated by Django 4.0.7 on 2023-06-14 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Адрес")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("1", "Обычная доставка"), ("2", "Экспресс доставка")],
                        default="1",
                        max_length=30,
                        verbose_name="Тип доставки",
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена доставки",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("1", "Онлайн картой"),
                            ("2", "Онлайн со случайного чужого счета"),
                        ],
                        default="1",
                        max_length=30,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменен"),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="оплачен")),
                (
                    "card_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10000000),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                        verbose_name="Номер карты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="статус платежа",
                    ),
                ),
                (
                    "payment_code",
                    models.IntegerField(default=0, verbose_name="Код оплаты"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_orders.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="app_shop.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товары",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
