# Generated by Django 4.0.7 on 2023-06-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_express",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена экспресс доставки",
                    ),
                ),
                (
                    "edge_for_free_delivery",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Порог бесплатной доставки",
                    ),
                ),
                (
                    "cost_usual_delivery",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена обычной доставки",
                    ),
                ),
                (
                    "quantity_popular",
                    models.PositiveIntegerField(
                        default=8,
                        verbose_name="Количество популярных товаров на главной странице",
                    ),
                ),
                (
                    "time_cache_product",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="Через какое кол-во дней кэшировать данные о продукте",
                    ),
                ),
                (
                    "category_main_page",
                    models.ManyToManyField(
                        to="app_shop.category",
                        verbose_name="Категории для показа на главной странице (не больше 3)",
                    ),
                ),
                (
                    "root_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_category",
                        to="app_shop.category",
                        verbose_name="Корневая категория каталога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация",
                "verbose_name_plural": "Конфигурация",
            },
        ),
    ]
